HTML and language
rms-open-letter/rms-open-letter.github.io pull request #2526
Opened 2021-03-27 22:50 UTC by Artoria2e5

The first commit should be harmless. It adds a `lang` attribute to pages, and it should really just affect the HTML output's said attribute.

The second commit relies on rms-open-letter/minima#5. The idea is to make the whole thing LTR so that actual markdown syntax can be used more easily. The fallback solution works by creating a div element around all the text when Jekyll's Liquid processor is not present.

If for some reason the minima PR is undesirable, I can just make the div element unconditional.

2021-03-28 00:14 UTC, ehashman requested changes

2021-03-28 00:14 UTC, ehashman commented on appendix.fa.md
> +{% endif %}
```suggestion
```

2021-03-28 00:14 UTC, ehashman commented on index.ar.md
> +{% endif %}
Can be removed

2021-03-28 00:14 UTC, ehashman commented on index.ar.md
> +{% endif %}
Can be removed.

2021-03-28 00:14 UTC, ehashman commented on index.fa.md
> +{% endif %}
Can be removed.

2021-03-28 00:14 UTC, ehashman commented on index.fa.md
> +{% endif %}
Can be removed.

2021-03-29 12:18 UTC, Artoria2e5 commented
Sorry for the delay. Working on removing the things now.

2021-03-29 19:18 UTC, ehashman commented
Will squash and merge this as a single commit.

2021-03-29 19:18 UTC, merged